USE Master
CREATE DATABASE BERSERK
GO
USE BERSERK
CREATE TABLE PRODUCTOS
(
	ID INT IDENTITY(1,1),
	EDITION VARCHAR(20),
	NOMBRE VARCHAR(100),
	FECHA_IMPRESION DATE,
	FECHA_PUBLICACION DATE,
	PRECIO MONEY,
	STOCK INT,
	RUTA_IMG VARCHAR(100)
		CONSTRAINT PRODUCTOS_PK PRIMARY KEY (ID)
);

CREATE TABLE CLIENTES
(
	USERNAME varchar(20),
	NOMBRE VARCHAR(20),
	APELLIDO VARCHAR(20),
	TELEFONO VARCHAR(10),
	CONSTRAINT CLIENTE_USERNAME_PK PRIMARY KEY (USERNAME)
);

CREATE TABLE ORDENES
(
	ORDER_ID INT IDENTITY(1000,1),
	CLIENTE VARCHAR(20),
	ID_PRODUCTO INT,
	CANTIDAD INT,
	FECHA_VENTA DATE CONSTRAINT DF_FECHA_VENTAS DEFAULT (GETDATE()),
	DIRECCION VARCHAR(100),
	PAIS VARCHAR(20),
	CONSTRAINT ORDENES_ORDER_PK PRIMARY KEY (ORDER_ID),
	CONSTRAINT ORDENES_ID_PRODUCTOS_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID),
	CONSTRAINT ORDENES_CLIENTE_FK FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (USERNAME)
);

GO
CREATE PROCEDURE INSERTAR_PRODUCTOS(
	@EDITION VARCHAR(20),
	@NOMBRE VARCHAR(20),
	@FECHA_IMPRESION DATE,
	@FECHA_PUBLICACION DATE,
	@PRECIO MONEY,
	@STOCK INT,
	@RUTA_IMG VARCHAR(100)
)
AS
BEGIN
	INSERT INTO PRODUCTOS
		(EDITION,NOMBRE,FECHA_IMPRESION,FECHA_PUBLICACION,PRECIO,STOCK,RUTA_IMG)
	VALUES
		(@EDITION, @NOMBRE, @FECHA_IMPRESION, @FECHA_PUBLICACION, @PRECIO, @STOCK, @RUTA_IMG)
END

GO
CREATE PROCEDURE ACTUALIZAR_STOCK(
	@ID INT,
	@STOCK INT
)
AS
BEGIN
	UPDATE PRODUCTOS
	SET 
		STOCK=@STOCK
	WHERE ID=@ID;
END

GO
create PROCEDURE INSERTAR_ORDENES(
	@CLIENTE VARCHAR(20),
	@ID_PRODUCTO INT,
	@CANTIDAD INT,
	@DIRECCION VARCHAR(100),
	@PAIS VARCHAR(20)
)
AS
BEGIN
	INSERT INTO ORDENES
		(CLIENTE,ID_PRODUCTO,CANTIDAD,DIRECCION,PAIS)
	VALUES
		(@CLIENTE, @ID_PRODUCTO, @CANTIDAD, @DIRECCION, @PAIS)
END

GO
Create TRIGGER ORDENES_VERIFICACION
ON ORDENES
INSTEAD OF INSERT AS
DECLARE 
		@CLIENTE VARCHAR(20),
		@ID_PRODUCTO INT,
		@CANTIDAD INT,
		@FECHA DATE,
		@DIRECCION VARCHAR(100),
		@PAIS VARCHAR(20)

	SELECT
	@CLIENTE = INSERTED.CLIENTE,
	@ID_PRODUCTO = INSERTED.ID_PRODUCTO,
	@CANTIDAD = INSERTED.CANTIDAD,
	@FECHA = INSERTED.FECHA_VENTA,
	@DIRECCION = INSERTED.DIRECCION,
	@PAIS = INSERTED.PAIS
FROM INSERTED

	IF (SELECT STOCK
FROM PRODUCTOS
WHERE ID=@ID_PRODUCTO)>@CANTIDAD
	BEGIN
	INSERT INTO ORDENES
		(CLIENTE,ID_PRODUCTO,CANTIDAD,FECHA_VENTA,DIRECCION,PAIS)
	VALUES
		(@CLIENTE, @ID_PRODUCTO, @CANTIDAD, @FECHA, @DIRECCION, @PAIS)

	UPDATE PRODUCTOS
		SET STOCK-=@CANTIDAD
		WHERE ID = @ID_PRODUCTO
END
	ELSE
	BEGIN
	PRINT 'NO HAY SUFICIENTE STOCK'
END

go
Create Procedure Insertar_Clientes(
	@usuario varchar(20),
	@nombre varchar(20),
	@apellido varchar(20),
	@telefono varchar(20)
)
AS
BEGIN
	insert into Clientes
		(USERNAME,NOMBRE,APELLIDO,TELEFONO)
	values(@usuario, @nombre, @apellido, @telefono)
END

INSERT INTO CLIENTES
VALUES
	('EliasP', 'Elias', 'Perez', '6302-3921'),
	('THEDAVIDFW', 'DAVID', 'FENG', '6240-3084')

INSERT INTO PRODUCTOS
	(EDITION,NOMBRE,FECHA_IMPRESION,FECHA_PUBLICACION,PRECIO,STOCK,RUTA_IMG)
VALUES
	('DELUXE', 'BERSERK DELUXE VOLUME 1', '2021-10-22', '2021-11-20', 35.99, 10, 'Imagenes/CelularVibrando.svg'),
	('STANDARD', 'BERSERK STANDARD VOLUME 1', '2021-10-22', '2021-11-20', 15.99, 10, 'Imagenes/Bombillo.svg')
